# Website Configuration
site:
  title: "Vue Docs UI Example"
  description: "Example documentation website built with Vue Docs UI"
  # Logo formats supported:
  # 1. emoji: "🤖"
  # 2. image URL: "https://example.com/logo.png"
  # 3. local image: "/images/logo.png"
  # 4. relative path: "./assets/logo.svg"
  logo: "📚"
  author: "Vue Docs UI Team"
  
# Navigation Bar Configuration
navbar:
  items:
    - title: "Home"
      link: "/"
      active: true
    - title: "Guide"
      link: "/guide"
    - title: "Advanced"
      link: "/advanced"
    - title: "Examples"
      link: "/examples"
    - title: "GitHub"
      link: "https://github.com/shenjianZ/vue-docs-ui"
      external: true

# Sidebar Navigation Configuration
sidebar:
  sections:
    - title: "Getting Started"
      path: "/guide"
      children:
        - title: "Introduction"
          path: "/guide/introduction"
        - title: "Installation"
          path: "/guide/installation"
        - title: "Quick Start"
          path: "/guide/quick-start"
        - title: "Configuration"
          path: "/guide/configuration"
          
    - title: "Advanced Guide"
      path: "/advanced"
      children:
        - title: "Custom Themes"
          path: "/advanced/themes"
        - title: "Component Development"
          path: "/advanced/components"
        - title: "API Reference"
          path: "/advanced/api"
        - title: "Deployment"
          path: "/advanced/deployment"
    
    - title: "Examples"
      path: "/examples"
      children:
        - title: "Basic Example"
          path: "/examples/basic"
          

# Theme Configuration
theme:
  # Default theme mode: 'light' | 'dark' | 'auto'
  # light: Force light mode
  # dark: Force dark mode
  # auto: Follow system preference (default)
  defaultMode: "auto"
  
  # Allow users to toggle theme (show theme toggle button)
  allowToggle: true
  
  # Color Configuration
  colors:
    primary: "#3b82f6"
    secondary: "#64748b"
    accent: "#06b6d4"
    background: "#ffffff"
    surface: "#f8fafc"
    text: "#1e293b"
    textSecondary: "#64748b"
    border: "#e2e8f0"
    
  fonts:
    primary: "Inter, -apple-system, BlinkMacSystemFont, sans-serif"
    mono: "JetBrains Mono, Consolas, monospace"

# Table of Contents Configuration
toc:
  # Maximum heading level to display in TOC (1-6)
  maxLevel: 2
  
  # Enable table of contents
  enabled: true
  
  # TOC title
  title: "On This Page" 

# Footer Configuration
footer:
  enabled: true
  copyright: "© 2024 Vue Docs UI. All rights reserved."
  repository:
    url: "https://github.com/your_github_id/your_repo_name"
    branch: "master"
  lastUpdated: "2024-12-19"
  links:
    - title: "Documentation"
      link: "/guide/introduction"
    - title: "GitHub"
      link: "https://github.com/your_github_id/your_repo_name"
      external: true
    - title: "License"
      link: "/license"
  social:
    - name: "email"
      url: "mailto:contact@example.com"
      icon: "mail"
    - name: "github"
      url: "https://github.com/your_github_id"
      icon: "github"
    # - name: "youtube"
    #   url: "https://youtube.com/@yourhandle"
    #   icon: "youtube"
    # - name: "twitter"
    #   url: "https://twitter.com/yourhandle"
    #   icon: "twitter"
    # - name: "discord"
    #   url: "https://discord.gg/yourinvite"
    #   icon: "discord"
    # - name: "telegram"
    #   url: "https://t.me/yourhandle"
    #   icon: "telegram"
    # - name: "tiktok"
    #   url: "https://tiktok.com/@yourhandle"
    #   icon: "tiktok"
    - name: "bilibili"
      url: "https://space.bilibili.com/your_bilibili_id"
      icon: "bilibili"
    - name: "qq"
      url: "mqqapi://card/show_pslcard?src_type=internal&version=1&uin=your_qq_id&card_type=person&source=qrcode"
      icon: "qq"
    - name: "wechat"
      url: "weixin://dl/add?your_wechat_id"
      icon: "wechat"
    # - name: "weibo"
    #   url: "https://weibo.com/yourhandle"
    #   icon: "weibo"
    # - name: "douyin"
    #   url: "https://www.douyin.com/user/yourhandle"
    #   icon: "douyin"
    # - name: "zhihu"
    #   url: "https://www.zhihu.com/people/yourhandle"
    #   icon: "zhihu" 