# 网站基本配置
site:
  title: "Vue Docs UI 示例项目"
  description: "基于 Vue Docs UI 构建的文档网站示例"
  # logo支持以下格式：
  # 1. emoji: "🤖"
  # 2. 图片URL: "https://example.com/logo.png"
  # 3. 本地图片: "/images/logo.png"
  # 4. 相对路径: "./assets/logo.svg"
  logo: "📚"
  author: "Vue Docs UI Team"
  
# 顶部导航配置
navbar:
  items:
    - title: "首页"
      link: "/"
      active: true
    - title: "指南"
      link: "/guide"
    - title: "进阶"
      link: "/advanced"
    - title: "示例"
      link: "/examples"
    - title: "GitHub"
      link: "https://github.com/shenjianZ/vue-docs-ui"
      external: true

# 侧边栏导航配置
sidebar:
  sections:
    - title: "快速开始"
      path: "/guide"
      children:
        - title: "介绍"
          path: "/guide/introduction"
        - title: "安装"
          path: "/guide/installation"
        - title: "快速上手"
          path: "/guide/quick-start"
        - title: "配置说明"
          path: "/guide/configuration"
          
    - title: "进阶指南"
      path: "/advanced"
      children:
        - title: "自定义主题"
          path: "/advanced/themes"
        - title: "组件开发"
          path: "/advanced/components"
        - title: "API 参考"
          path: "/advanced/api"
        - title: "部署"
          path: "/advanced/deployment"
          
    - title: "示例"
      path: "/examples"
      children:
        - title: "基础示例"
          path: "/examples/basic"

# Theme Configuration
theme:
  # Default theme mode: 'light' | 'dark' | 'auto'
  # light: Force light mode
  # dark: Force dark mode
  # auto: Follow system preference (default)
  defaultMode: "auto"
  
  # Allow users to toggle theme (show theme toggle button)
  allowToggle: true
  
  # Color Configuration
  colors:
    primary: "#3b82f6"
    secondary: "#64748b"
    accent: "#06b6d4"
    background: "#ffffff"
    surface: "#f8fafc"
    text: "#1e293b"
    textSecondary: "#64748b"
    border: "#e2e8f0"
    success: "#10b981"
    warning: "#f59e0b"
    error: "#ef4444"
    
  fonts:
    primary: "Inter, -apple-system, BlinkMacSystemFont, sans-serif"
    mono: "JetBrains Mono, Consolas, Monaco, monospace"
    
  # Layout Configuration
  layout:
    headerHeight: "60px"
    sidebarWidth: "280px"
    tocWidth: "240px"
    contentMaxWidth: "1200px"

# Table of Contents Configuration
toc:
  # Maximum heading level to display in TOC (1-6)
  maxLevel: 3
  
  # Enable table of contents
  enabled: true
  
  # TOC title
  title: "本页目录"
  
  # Show TOC on mobile devices
  showOnMobile: false

# Footer Configuration
footer:
  enabled: true
  copyright: "© 2024 Vue Docs UI. All rights reserved."
  repository:
    url: "https://github.com/your_github_id/your_repo_name"
    branch: "master"
  lastUpdated: "2024-12-19"
  links:
    - title: "Documentation"
      link: "/guide/introduction"
    - title: "GitHub"
      link: "https://github.com/your_github_id/your_repo_name"
      external: true
    - title: "License"
      link: "/license"
  social:
    - name: "email"
      url: "mailto:contact@example.com"
      icon: "mail"
    - name: "github"
      url: "https://github.com/your_github_id"
      icon: "github"
    # - name: "youtube"
    #   url: "https://youtube.com/@yourhandle"
    #   icon: "youtube"
    # - name: "twitter"
    #   url: "https://twitter.com/yourhandle"
    #   icon: "twitter"
    # - name: "discord"
    #   url: "https://discord.gg/yourinvite"
    #   icon: "discord"
    # - name: "telegram"
    #   url: "https://t.me/yourhandle"
    #   icon: "telegram"
    # - name: "tiktok"
    #   url: "https://tiktok.com/@yourhandle"
    #   icon: "tiktok"
    - name: "bilibili"
      url: "https://space.bilibili.com/your_bilibili_id"
      icon: "bilibili"
    - name: "qq"
      url: "mqqapi://card/show_pslcard?src_type=internal&version=1&uin=your_qq_id&card_type=person&source=qrcode"
      icon: "qq"
    - name: "wechat"
      url: "weixin://dl/add?your_wechat_id"
      icon: "wechat"
    # - name: "weibo"
    #   url: "https://weibo.com/yourhandle"
    #   icon: "weibo"
    # - name: "douyin"
    #   url: "https://www.douyin.com/user/yourhandle"
    #   icon: "douyin"
    # - name: "zhihu"
    #   url: "https://www.zhihu.com/people/yourhandle"
    #   icon: "zhihu" 

# Analytics Configuration
analytics:
  # Google Analytics
  google:
    enabled: false
    id: ""
  
  # Other analytics providers can be added here

# PWA Configuration
pwa:
  enabled: false
  name: "Vue Docs UI"
  shortName: "VueDocsUI"
  description: "Beautiful documentation websites made simple"
  themeColor: "#3b82f6"
  backgroundColor: "#ffffff" 